import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Nav from "@/components/Nav";
import ReactQueryProvider from "@/components/ReactQuery";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen dark bg-background antialiased",
          inter.className
        )}
      >
        <main className="max-w-6xl mx-auto px-4 space-y-8 pb-10">
          <ReactQueryProvider>
            <Nav />
            {children}
          </ReactQueryProvider>
        </main>
      </body>
    </html>
  );
}
